for travis-ci.org build with SDL2
set  -mmacosx-version-min=10.6 instead of 10.5 to avoid

/usr/local/include/SDL2/SDL_platform.h:87:3: error: SDL for Mac OS X only supports deploying on 10.6 and above.